[project]
name = "docmind"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.135.2",
    "inngest>=0.5.18",
    "pypdf>=4.0.0",
    "openai>=2.29.0",
    "python-dotenv>=1.2.2",
    "qdrant-client>=1.17.1",
    "sentence-transformers==2.7.0",
    "streamlit>=1.55.0",
    "uvicorn>=0.42.0",
]